# Generated by Django 3.2.8 on 2021-10-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211025_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='ratings',
        ),
    ]
