# Generated by Django 3.2.8 on 2021-10-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_rating_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratings',
            new_name='rating',
        ),
    ]
