const products = [
{
    '_id' : '1',
    'name' : 'macbook',
    'image' : '/images/macbook.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Apple',
    'category' :'Laptop',
    'price' : '1050',
    'numInStock' : 10,
    'ratings' : 4.7,
    'numReviews' : 10,
},
{
    '_id' : '2',
    'name' : 'iphone10',
    'image' : '/images/iphone10.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Apple',
    'category' :'Phone',
    'price' : '730',
    'numInStock' : 20,
    'ratings' : 4.5,
    'numReviews' : 12,
},
{
    '_id' : '3',
    'name' : 'Apple watch',
    'image' : '/images/applewatch2.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Apple',
    'category' :'Watch',
    'price' : '800',
    'numInStock' : 5,
    'ratings' : 4.5,
    'numReviews' : 10,
},
{
    '_id' : '4',
    'name' : 'Apple airpods',
    'image' : '/images/airpods.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Apple',
    'category' :'Earbuds',
    'price' : '655',
    'numInStock' : 9,
    'ratings' : 4.8,
    'numReviews' : 10,
},
{
    '_id' : '5',
    'name' : 'iMac ',
    'image' : '/images/imac.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'apple',
    'category' :'Desktop',
    'price' : '1899',
    'numInStock' : 3,
    'ratings' : 4.2,
    'numReviews' : 20,
},
{
    '_id' : '6',
    'name' : 'Alexa',
    'image' : '/images/alexa.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Amazon',
    'category' :'Smart Home',
    'price' : '299',
    'numInStock' : 21,
    'ratings' : 4.3,
    'numReviews' : 5,
},
{
    '_id' : '7',
    'name' : 'Mechanical Keyboard',
    'image' : '/images/keyboarddark.jpg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Havit',
    'category' :'keyboard',
    'price' : '199.99',
    'numInStock' : 23,
    'ratings' : 3.4,
    'numReviews' : 10,
},
{
    '_id' : '8',
    'name' : 'Butterfly Keyboard',
    'image' : '/images/keyboard.jpg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Apple',
    'category' :'keyboard',
    'price' : '399.99',
    'numInStock' : 3,
    'ratings' : 2.5,
    'numReviews' : 10,
},
{
    '_id' : '9',
    'name' : 'Nikon Camera',
    'image' : '/images/nikon.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Nikon',
    'category' :'camera',
    'price' : '1199.99',
    'numInStock' : 0,
    'ratings' : 3.8,
    'numReviews' : 10,
},
{
    '_id' : '19',
    'name' : 'Apple Watch Series',
    'image' : '/images/applewatch1.jpeg',
    'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis eget velit. Mattis nunc sed blandit libero volutpat sed. Lacus sed turpis tincidunt id aliquet risus. Pellentesque nec nam aliquam sem et tortor.',
    'brand' : 'Apple',
    'category' :'watch',
    'price' : '299.99',
    'numInStock' : 3,
    'ratings' : 3.1,
    'numReviews' : 12,
},
]

export default products 